services:
  client:
    image: pandadoker/client:2
    build:
      context: ./client
      # args:
      #   REACT_APP_LINK: ${REACT_APP_LINK}
      #   REACT_APP_WS: ${REACT_APP_WS}
      #   REACT_APP_BOTLINK: ${REACT_APP_BOTLINK}
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    image: pandadoker/server:2
    build:
      context: ./server
    container_name: server
    depends_on:
        db:
          condition: service_healthy
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env.production

  db:
    image: mongo
    container_name: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/serviceapp --quiet
      # interval: 5s
      # timeout: 5s
      # retries: 5
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /home/panda/mongodata:/data/db
      - /home/panda/mongodump:/dump




