services:

  client:
    image: pandadoker/sa-client-1:v1
    container_name: client
    build:
      context: ./client
      target: artifact

  client2:
    image: pandadoker/sa-client-2:v1
    container_name: site
    build:
      context: ./site

  server:
    image: pandadoker/sa-server:v1
    container_name: server
    build:
      context: ./server
