interface LengData {
    rutext: string
    index: string
    info_data: string
    update?: boolean
}

interface LengDataStart {
    title: string
    index: string
    info: string
}

export const lengs: LengDataStart[] = [
    {title: 'Русский', index: 'ru', info: 'русский'},
    {title: 'English', index: 'en', info: 'английский'},
    {title: 'Español', index: 'es', info: 'испанский'},
    {title: 'Français', index: 'fr', info: 'французский'},
    {title: 'Português', index: 'pt', info: 'португальский'},
    {title: 'Deutsch', index: 'de', info: 'немецкий'},
    {title: '中文', index: 'zh', info: 'китайский'},
    {title: 'Italiano', index: 'it', info: 'итальянский'},
    {title: '日本語', index: 'ja', info: 'японский'},
    {title: '한국어', index: 'ko', info: 'корейский'},
    {title: 'العربية', index: 'ar', info: 'арабский'},
    {title: 'हिन्दी', index: 'hi', info: 'хинди'},
    {title: 'עברית', index: 'he', info: 'иврит'},
    {title: 'Türkçe', index: 'tr', info: 'турецкий'},
    {title: 'Tiếng Việt', index: 'vi', info: 'вьетнамский'},
    {title: 'Nederlands', index: 'nl', info: 'голландский'},
    {title: 'Polski', index: 'pl', info: 'польский'},
    {title: 'Bahasa Indonesia', index: 'id', info: 'индонезийский'},
    {title: 'Svenska', index: 'sv', info: 'шведский'},
    {title: 'Čeština', index: 'cs', info: 'чешский'},
    {title: 'Українська', index: 'uk', info: 'украинский'},
    {title: 'Magyar', index: 'hu', info: 'венгерский'},
    {title: 'ไทย', index: 'th', info: 'тайский'},
    {title: 'Ελληνικά', index: 'el', info: 'греческий'},
    {title: 'Dansk', index: 'da', info: 'датский'},
    {title: 'Suomi', index: 'fi', info: 'финский'},
    {title: 'Română', index: 'ro', info: 'румынский'},
    {title: 'Slovenčina', index: 'sk', info: 'словацкий'},
    {title: 'Беларуская', index: 'be', info: 'белорусский'}
]

export const textArray: LengData[] = [
    {rutext: 'Привет', index: 'hello', info_data: 'приветствие'},
    {rutext: 'Пользователь не найден или произошла ошибка', index: 'userError1', info_data: 'юзер не найден'},
    {rutext: 'Пользователь уже существует', index: 'existUser', info_data: 'юзер существует'},
    {rutext: 'Временный пароль выслан на почту', index: 'codeSendToEmail', info_data: 'пароль на почту выслан'},
    {rutext: 'Временный пароль', index: 'newCode', info_data: 'временный пароль'},
    {rutext: 'Добро пожаловать!', index: 'welcome', info_data: 'добро пожаловать'},
    {rutext: 'Войти', index: 'login', info_data: 'войти'},
    {rutext: 'Отправить сеансовый пароль на почту', index: 'sendPasswordToEmail', info_data: 'отправить парол на почту'},
    {rutext: 'Невалидный емейл', index: 'badEmail', info_data: 'невалидный емейл'},
    {rutext: 'Выход', index: 'exit', info_data: 'выход'},
    {rutext: 'Авторизоваться', index: 'auth', info_data: 'авторизоваться'},
    {rutext: 'Мы создаем новый сервис для вас. Пожалуйста подождите...', index: 'newServiceCreating', info_data: 'создаем сервис ожидание'},
    {rutext: 'Настройка сервиса', index: 'serviceSettings', info_data: 'настройки сервиса'},
    {rutext: 'Создать заказ', index: 'createOrder', info_data: 'создать заказ'},
    {rutext: 'Заказы', index: 'orders', info_data: 'заказы'},
    {rutext: 'Сохранить', index: 'save', info_data: 'сохранить'},
    {rutext: 'Новое имя для сервиса', index: 'newNameForService', info_data: 'новое имя для сервиса'},
    {rutext: 'Новое имя для локального сервиса', index: 'newNameForSubService', info_data: 'новое имя для локального сервиса'},
    {rutext: 'Изменение имени сервиса', index: 'editingNameService', info_data: 'изменение имени сервиса'},
    {rutext: 'Название сервиса', index: 'changeNameMainService', info_data: 'изменение имени сервиса', update: false},
    {rutext: 'Название локального сервиса', index: 'changeNameSubService', info_data: 'изменение имени локального сервиса', update: false},
    {rutext: 'Список девайсов', index: 'changeServiceDeviceList', info_data: 'список девайсов', update: false},
    {rutext: 'Название девайса (примеры: Ноутбук, Холодильник, Кот)', index: 'deviceName', info_data: 'название девайса', update: false},
    {rutext: 'Добавить', index: 'add', info_data: 'добавить', update: false},
    {rutext: 'Статусы', index: 'changeServiceStatusList', info_data: 'статусы', update: false},
    {rutext: 'Статус (примеры: Готов, Ожидает запчасти, На согласовании)', index: 'statusName', info_data: 'название статуса', update: false},
    {rutext: 'Роли', index: 'changeServiceRole', info_data: 'роли', update: false},
    {rutext: 'Новая роль', index: 'newRole', info_data: 'новая роль', update: false},
    {rutext: 'Пользователи', index: 'changeServiceUser', info_data: 'юзеры', update: false},
    {rutext: 'Локальные сервисы', index: 'changeLocalService', info_data: 'Локальные сервисы', update: false},
    {rutext: 'Настройки локального сервиса', index: 'serviceLocalSettings', info_data: 'настройки локального сервиса', update: false},
    {rutext: 'Имя для нового локального сервиса', index: 'newNameForLocalService', info_data: 'новое имя для локального сервиса'},
    {rutext: 'Для входа перелогиниться!', index: 'outLoginForEnter', info_data: 'перелогиниться для входа'},
    {rutext: 'Рабочее время', index: 'changeTimeSubService', info_data: 'рабочее время'},
    {rutext: 'Неустановлено', index: 'notSet', info_data: 'неустановлено'},
    {rutext: 'Время работы (пример: с 10:00 до 12:00, понедельник - пятница, выходной: воскресенье)', index: 'workTime', info_data: 'установка время работы', update: false},
    {rutext: 'Контакты', index: 'changeContactSubService', info_data: 'контакты'},
    {rutext: 'Контакты (пример: +334 355 6464646)', index: 'workContact', info_data: 'установка контактов'},
    {rutext: 'Адрес', index: 'changeAddressSubService', info_data: 'адрес'},
    {rutext: 'Адрес (пример: Северный полюс, Берлога №7, комната 5)', index: 'workAddress', info_data: 'установка адреса'},
    {rutext: 'Девайсы', index: 'devices', info_data: 'девайсы'},
    {rutext: 'Удалить пользователя и полностью отключить доступ ко всем сервисам', index: 'deletUser', info_data: 'удалитьпользователя'},
    {rutext: 'Доступ пользователя к определенным статусам заказов', index: 'deletStatus', info_data: 'удалитьстатуст'},
    {rutext: 'Доступ пользователя к определенным девайсам заказов', index: 'deletDevice', info_data: 'удалитьдевайс'},
    {rutext: 'Локальные пользователи', index: 'changeLocalServiceUser', info_data: 'локальные пользователи', update: false},
    {rutext: 'Мои настройки', index: 'changeMyUser', info_data: 'мои настройки', update: false},
    {rutext: 'Имя пользователя', index: 'changeMyName', info_data: 'имя пользователя', update: false},
    {rutext: 'Имя', index: 'name', info_data: 'имя', update: false},
    {rutext: 'Создать новый сервис', index: 'createService', info_data: 'создать новый сервис', update: false},
    {rutext: 'Удаление сервиса', index: 'deleteService', info_data: 'удаление сервиса', update: false},
    {rutext: 'Безвозвратно удалить сервис', index: 'deleteServiceWarning', info_data: 'удаление сервиса безвозвратное', update: false},
    {rutext: 'Информация о заказе', index: 'changeServiceOrderDataList', info_data: 'информация о заказе', update: false},
    {rutext: 'Удалить', index: 'delete', info_data: 'удалить', update: false},
    {rutext: 'Варианты', index: 'variants', info_data: 'варианты', update: false},
    {rutext: 'Очистить форму', index: 'clearForm', info_data: 'очистить форму', update: false},
    {rutext: 'Создать заказ', index: 'createNewOrder', info_data: 'создать новый заказ', update: false},
    {rutext: 'Менеджер', index: 'manager', info_data: 'менеджер', update: false},
    {rutext: 'Данные компании', index: 'changeInfoMainService', info_data: 'данные компании', update: false},
    {rutext: 'Отмена', index: 'cancel', info_data: 'отмена', update: false},
    {rutext: 'Цвета статусов', index: 'changeColorStatus', info_data: 'цвета статусов', update: false},
    {rutext: 'Настройка вида заказа', index: 'changeMyMainOrderDataLine', info_data: 'настройка вида  заказа', update: false},
    {rutext: 'Локальный сервис', index: 'localService', info_data: 'локальный сервис', update: false},
    {rutext: 'Статус', index: 'status', info_data: 'статус', update: false},
    {rutext: 'Создан', index: 'created', info_data: 'создан', update: false},
    {rutext: 'Изменён', index: 'edited', info_data: 'изменён', update: false},
    {rutext: 'Информация', index: 'information', info_data: 'нформация', update: false},
    {rutext: 'История', index: 'history', info_data: 'история', update: false},
    {rutext: 'Закрыть', index: 'close', info_data: 'закрыть', update: false},
    {rutext: 'Работы', index: 'works', info_data: 'работы', update: false},
    {rutext: 'Добавить запчасть', index: 'addPart', info_data: 'добавить запчасть', update: false},
    {rutext: 'Очистить', index: 'clear', info_data: 'очистить', update: false},
    {rutext: 'Услуга или запчасть', index: 'servOrPart', info_data: 'услуга или деталь', update: false},
    {rutext: 'Мастер', index: 'master', info_data: 'мастер', update: false},
    {rutext: 'Гарантия', index: 'varanty', info_data: 'гарантия', update: false},
    {rutext: 'Затраты', index: 'subCost', info_data: 'затраты', update: false},
    {rutext: 'Стоимость', index: 'cost', info_data: 'стоимость', update: false},
    {rutext: 'Удалить всё', index: 'deleteAll', info_data: 'удалить всё', update: false},
    {rutext: 'Обновлено', index: 'updated', info_data: 'обновлено', update: false},
    {rutext: 'Заказы', index: 'getOrdersCount', info_data: 'получение заказов', update: false},
    {rutext: 'Налог', index: 'changeFeeService', info_data: 'налог', update: false},
    {rutext: 'Устройство', index: 'device', info_data: 'устройство', update: false},
    {rutext: 'Привязка приложения Телеграм', index: 'сhangeMyTelegram', info_data: 'телеграм привязка', update: false},
    {rutext: 'Подпись заказчика', index: 'signClient', info_data: 'подпись заказчика', update: false},
    {rutext: 'Подпись менеджера', index: 'signManager', info_data: 'подпись менеджера', update: false},
    {rutext: 'Документы', index: 'documents', info_data: 'документы', update: false},
    {rutext: 'Новый заказ', index: 'NewOrderPrint', info_data: 'новый заказ', update: false},
    {rutext: 'Закрыть заказ', index: 'closeOrder', info_data: 'закрыть заказ', update: false},
    {rutext: 'Печать', index: 'print', info_data: 'печать', update: false},
    
]
